name: 🚀 Deploy website on push

on:
  push:
    branches:
      - main

jobs:
  web-deploy:
    name: 🎉 Deploy
    runs-on: ubuntu-latest
    environment: production

    steps:
    - name: 🚚 Get latest code
      uses: actions/checkout@v3

    - name: 📂 SFTP Deploy
      uses: wlixcc/SFTP-Deploy-Action@v1.2.4
      with:
        username: ${{ secrets.HOSTINGER_USERNAME }}
        server: ${{ secrets.HOSTINGER_HOST }}
        port: 22
        local_path: './*'
        remote_path: '/home/u727308653/domains/brasilemdobro.com.br/public_html/gestao'
        password: ${{ secrets.SFTP_PASSWORD }}